---
name: main
on:
  push:
    branches: [main]
jobs:
  deploy:
    uses: ./.github/workflows/wc-deploy.yaml
    permissions:
      contents: write
    with:
      is_pr: false
    secrets:
      app_id: ${{ secrets.APP_ID }}
      private_key: ${{ secrets.APP_PRIVATE_KEY }}
