---
name: test
on: pull_request
permissions: {}
env:
  AQUA_LOG_COLOR: always
jobs:
  status-check:
    uses: ./.github/workflows/wc-deploy.yaml
    permissions:
      contents: write
    with:
      is_pr: true
